# Lab 2: Working with Dictionary and DataFrame

## Part I: Working with Dictionary

- **A data structure used to store data in key-value pairs.**
```python
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE"
}
```

### Tasks: Perform following operations

| **Operation** | **Syntax** | **Example** |
|---------------|------------|-------------|
| Create dictionary | `d = {}` | `d = {"a": 1, "b": 2}` |
| Access value | `d[key]` | `d["a"]` |
| Use get() | `d.get(key)` | `d.get("a")` |
| Add item | `d[key] = value` | `d["c"] = 3` |
| Update value | `d[key] = new_value` | `d["a"] = 10` |
| Remove item using del() | `del d[key]` | `del d["b"]` |
| Remove using pop() | `d.pop(key)` | `d.pop("a")` |
| Remove last item | `d.popitem()` | `d.popitem()` |
| Clear dictionary | `d.clear()` | `d.clear()` |
| Copy dictionary | `d.copy()` | `d.copy()` |
| Get all keys | `d.keys()` | `d.keys()` |
| Get all values | `d.values()` | `d.values()` |
| Get all items | `d.items()` | `d.items()` |
| Check key exists | `key in d` | `"a" in d` |
| Get length | `len(d)` | `len(d)` |
| Loop through keys | `for k in d:` | `for k in d:` |
| Loop through values | `for v in d.values():` | `for v in d.values():` |
| Loop through items | `for k, v in d.items():` | `for k, v in d.items():` |

In [1]:
# Create dictionary
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE"
}

student

{'name': 'Ram', 'age': 20, 'faculty': 'BCE'}

In [2]:
# Access dictionary values
student["name"]

'Ram'

In [3]:
# Use get() method to access values
student.get("age")

20

In [4]:
# Add item
student["grade"] = "A"
student

{'name': 'Ram', 'age': 20, 'faculty': 'BCE', 'grade': 'A'}

In [5]:
# Update value
student["age"] = 21
student

{'name': 'Ram', 'age': 21, 'faculty': 'BCE', 'grade': 'A'}

In [6]:
# Remove item using del() method
del student["faculty"]

In [7]:
# Remove item using pop() method
student.pop("grade")
student

{'name': 'Ram', 'age': 21}

In [8]:
# Remove last item using popitem() method
student.popitem()
student

{'name': 'Ram'}

In [9]:
# Clear dictionary
student.clear()
student

{}

In [10]:
# Add some items again
student["name"] = "Ram"
student["age"] = 21
student

{'name': 'Ram', 'age': 21}

In [11]:
# Copy dictionary
new_student = student.copy()
new_student

{'name': 'Ram', 'age': 21}

In [12]:
# Get all keys
student.keys()

dict_keys(['name', 'age'])

In [13]:
# Get all values
student.values()

dict_values(['Ram', 21])

In [14]:
# Get all items
student.items()

dict_items([('name', 'Ram'), ('age', 21)])

In [15]:
# Check if kdy exists
"name" in student

True

In [16]:
#  Get length of dictionary
len(student)

2

In [17]:
# Loop through keys
for key in student:
    print(key)

name
age

In [18]:
# Loop through values
for value in student.values():
    print(value)

Ram
21

In [19]:
# Loop through items
for key, value in student.items():
    print(f"{key}: {value}")

name: Ram
age: 21

## Part II: Working with Pandas DataFrame

A DataFrame in Python is a two-dimensional, tabular data structure that organizes
data into labeled rows and columns. It is conceptually identical to an Excel
spreadsheet or a SQL table, making it the primary tool for data manipulation and
analysis in the Pandas Library.

| Task | Syntax |
|---|---|
| Create a DataFrame containing student details such as Name, Age, and Marks. | `df = pd.DataFrame()` |
| Display the first 5 rows of the DataFrame. | `df.head()` |
| Display the last 5 rows of the DataFrame. | `df.tail()` |
| Find the total number of rows and columns in the DataFrame. | `df.shape` |
| Display all column names in the DataFrame. | `df.columns` |
| Display complete information about the DataFrame including data types and memory usage. | `df.info()` |
| Generate a statistical summary of numerical columns in the DataFrame. | `df.describe()` |
| Select and display the Name column from the DataFrame. | `df['Name']` |
| Select and display multiple columns such as Name and Marks. | `df[['Name', 'Marks']]` |
| Display the first row of the DataFrame using positional indexing. | `df.iloc[0]` |
| Display the first row of the DataFrame using label-based indexing. | `df.loc[0]` |
| Access a specific cell value such as Marks of the first student. | `df.loc[0, 'Marks']` |
| Filter and display students whose Marks are greater than 80. | `df[df['Marks'] > 80]` |
| Filter and display students whose Age is greater than 20 and Marks are greater than 75. | `df[(df['Age'] > 20) & (df['Marks'] > 75)]` |
| Add a new column called Grade to the DataFrame. | `df['Grade'] = ['A', 'B']` |
| Increase all students’ Marks by 5. | `df['Marks'] = df['Marks'] + 5` |
| Update the Marks of Ram to 95 using a condition. | `df.loc[df['Name'] == 'Ram', 'Marks'] = 95` |
| Remove the Age column from the DataFrame. | `df.drop('Age', axis=1)` |
| Remove the first row from the DataFrame. | `df.drop(0, axis=0)` |
| Sort the DataFrame by Marks in ascending order. | `df.sort_values('Marks')` |
| Sort the DataFrame by Marks in descending order. | `df.sort_values('Marks', ascending=False)` |
| Concatenate two DataFrames vertically. | `pd.concat([df1, df2])` |
| Read data from a CSV file into a DataFrame. | `pd.read_csv('file.csv')` |
| Write the DataFrame into a CSV file. | `df.to_csv('file.csv')` |
| Read data from an Excel file into a DataFrame. | `pd.read_excel('file.xlsx')` |
| Write the DataFrame into an Excel file. | `df.to_excel('file.xlsx')` |

In [20]:
import pandas as pd

In [21]:
# Create a dictionary with student details
student_dict = {
    "Name": ["Ram", "Shyam", "Sita", "Gita", "Hari", "Maya", "Rita", "Suresh", "Ramesh", "Sanjay"],
    "Age": [20, 21, 19, 22, 20, 21, 19, 23, 20, 22],
    "Marks": [85, 90, 95, 88, 92, 87, 93, 89, 91, 86]
}

student_dict

{'Name': ['Ram',
  'Shyam',
  'Sita',
  'Gita',
  'Hari',
  'Maya',
  'Rita',
  'Suresh',
  'Ramesh',
  'Sanjay'],
 'Age': [20, 21, 19, 22, 20, 21, 19, 23, 20, 22],
 'Marks': [85, 90, 95, 88, 92, 87, 93, 89, 91, 86]}

In [22]:
# Create a DataFrame containing student details such as Name, Age, and Marks from the above dictionary.
dataframe = pd.DataFrame(student_dict)

dataframe

     Name  Age  Marks
0     Ram   20     85
1   Shyam   21     90
2    Sita   19     95
3    Gita   22     88
4    Hari   20     92
5    Maya   21     87
6    Rita   19     93
7  Suresh   23     89
8  Ramesh   20     91
9  Sanjay   22     86

In [23]:
# Display the first 5 rows of the DataFrame.
dataframe.head(5)

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     90
2   Sita   19     95
3   Gita   22     88
4   Hari   20     92

In [24]:
# Display the last 5 rows of the DataFrame.
dataframe.tail(5)

     Name  Age  Marks
5    Maya   21     87
6    Rita   19     93
7  Suresh   23     89
8  Ramesh   20     91
9  Sanjay   22     86

In [25]:
#  Find the total number of rows and columns in the DataFrame.
dataframe.shape

(10, 3)

In [26]:
#  Display all column names in the DataFrame.
dataframe.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [27]:
#  Display complete information about the DataFrame including data types and memory usage.
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
 2   Marks   10 non-null     int64
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

In [28]:
# Generate a statistical summary of numerical columns in the DataFrame.
dataframe.describe()

             Age      Marks
count  10.000000  10.000000
mean   20.700000  89.600000
std     1.337494   3.204164
min    19.000000  85.000000
25%    20.000000  87.250000
50%    20.500000  89.500000
75%    21.750000  91.750000
max    23.000000  95.000000

In [29]:
# Select and display the Name column from the DataFrame.
dataframe["Name"]

0       Ram
1     Shyam
2      Sita
3      Gita
4      Hari
5      Maya
6      Rita
7    Suresh
8    Ramesh
9    Sanjay
Name: Name, dtype: str

In [30]:
# Select and display multiple columns such as Name and Marks.
dataframe[["Name", "Marks"]]

     Name  Marks
0     Ram     85
1   Shyam     90
2    Sita     95
3    Gita     88
4    Hari     92
5    Maya     87
6    Rita     93
7  Suresh     89
8  Ramesh     91
9  Sanjay     86

In [31]:
# Display the first row of the DataFrame using positional indexing. 
dataframe.iloc[0]

Name     Ram
Age       20
Marks     85
Name: 0, dtype: object

In [32]:
# Display the first row of the DataFrame using label-based indexing.
dataframe.loc[0]

Name     Ram
Age       20
Marks     85
Name: 0, dtype: object

In [33]:
#  Access a specific cell value such as Marks of the first student.
dataframe.loc[0, "Marks"]

np.int64(85)

In [34]:
#  Filter and display students whose Marks are greater than 80
dataframe[dataframe["Marks"] > 80]

     Name  Age  Marks
0     Ram   20     85
1   Shyam   21     90
2    Sita   19     95
3    Gita   22     88
4    Hari   20     92
5    Maya   21     87
6    Rita   19     93
7  Suresh   23     89
8  Ramesh   20     91
9  Sanjay   22     86

In [35]:
# Filter and display students whose Age is greater than 20 and Marks are greater than 75
dataframe[(dataframe.Age > 20) & (dataframe.Marks > 75)]

     Name  Age  Marks
1   Shyam   21     90
3    Gita   22     88
5    Maya   21     87
7  Suresh   23     89
9  Sanjay   22     86

In [36]:
# Add a new column called Grade to the DataFrame.
dataframe["Grade"] = ["A", "B", "A", "B", "A", "B", "A", "B", "A", "B"]

dataframe

     Name  Age  Marks Grade
0     Ram   20     85     A
1   Shyam   21     90     B
2    Sita   19     95     A
3    Gita   22     88     B
4    Hari   20     92     A
5    Maya   21     87     B
6    Rita   19     93     A
7  Suresh   23     89     B
8  Ramesh   20     91     A
9  Sanjay   22     86     B

In [37]:
# Increase all students’ Marks by 5.
dataframe["Marks"] = dataframe["Marks"] + 5

dataframe

     Name  Age  Marks Grade
0     Ram   20     90     A
1   Shyam   21     95     B
2    Sita   19    100     A
3    Gita   22     93     B
4    Hari   20     97     A
5    Maya   21     92     B
6    Rita   19     98     A
7  Suresh   23     94     B
8  Ramesh   20     96     A
9  Sanjay   22     91     B

In [38]:
#  Update the Marks of Ram to 95 using a condition.
dataframe.loc[dataframe["Name"] == "Ram", "Marks"] = 95

dataframe

     Name  Age  Marks Grade
0     Ram   20     95     A
1   Shyam   21     95     B
2    Sita   19    100     A
3    Gita   22     93     B
4    Hari   20     97     A
5    Maya   21     92     B
6    Rita   19     98     A
7  Suresh   23     94     B
8  Ramesh   20     96     A
9  Sanjay   22     91     B

In [39]:
# Remove the Age column from the DataFrame
dataframe.drop("Age", axis=1, inplace=True)

dataframe

     Name  Marks Grade
0     Ram     95     A
1   Shyam     95     B
2    Sita    100     A
3    Gita     93     B
4    Hari     97     A
5    Maya     92     B
6    Rita     98     A
7  Suresh     94     B
8  Ramesh     96     A
9  Sanjay     91     B

In [40]:
# Remove the first row from the DataFrame.
dataframe.drop(0, axis=0, inplace=True)

dataframe

     Name  Marks Grade
1   Shyam     95     B
2    Sita    100     A
3    Gita     93     B
4    Hari     97     A
5    Maya     92     B
6    Rita     98     A
7  Suresh     94     B
8  Ramesh     96     A
9  Sanjay     91     B

In [41]:
# Sort the DataFrame by Marks in ascending order. 
dataframe.sort_values("Marks", inplace=True)

dataframe

     Name  Marks Grade
9  Sanjay     91     B
5    Maya     92     B
3    Gita     93     B
7  Suresh     94     B
1   Shyam     95     B
8  Ramesh     96     A
4    Hari     97     A
6    Rita     98     A
2    Sita    100     A

In [42]:
# Sort the DataFrame by Marks in descending order.
dataframe.sort_values(by="Marks", ascending=False, inplace=True)

dataframe

     Name  Marks Grade
2    Sita    100     A
6    Rita     98     A
4    Hari     97     A
8  Ramesh     96     A
1   Shyam     95     B
7  Suresh     94     B
3    Gita     93     B
5    Maya     92     B
9  Sanjay     91     B

In [43]:
#  Concatenate two DataFrames vertically.
dataframe2 = pd.DataFrame({
    "Name": ["Anita", "Suresh"],
    "Marks": [88, 92],
    "Grade": ["B", "A"]
})

pd.concat([dataframe, dataframe2])
dataframe

     Name  Marks Grade
2    Sita    100     A
6    Rita     98     A
4    Hari     97     A
8  Ramesh     96     A
1   Shyam     95     B
7  Suresh     94     B
3    Gita     93     B
5    Maya     92     B
9  Sanjay     91     B

In [44]:
# Write the DataFrame into a CSV file.
dataframe.to_csv("./assets/lab02-output.csv", index=False)

In [45]:
# Read data from a CSV file into a DataFrame.
df = pd.read_csv("./assets/lab02-output.csv")

df

     Name  Marks Grade
0    Sita    100     A
1    Rita     98     A
2    Hari     97     A
3  Ramesh     96     A
4   Shyam     95     B
5  Suresh     94     B
6    Gita     93     B
7    Maya     92     B
8  Sanjay     91     B

In [46]:
# Write the DataFrame into an Excel file.
import openpyxl

df.to_excel("./assets/lab02-output.xlsx", index=False)

In [47]:
# Read data from an Excel file into a DataFrame.
excel_df = pd.read_excel("./assets/lab02-output.xlsx")

excel_df

     Name  Marks Grade
0    Sita    100     A
1    Rita     98     A
2    Hari     97     A
3  Ramesh     96     A
4   Shyam     95     B
5  Suresh     94     B
6    Gita     93     B
7    Maya     92     B
8  Sanjay     91     B

## Conclusion

In this lab experiment, we learnt about the python dictionaries and pandas DataFrame data types.
Now, we are confident in working with the python dictionaries and pandas DataFrames.